#!/bin/bash
echo 'PIPELINE 3DE WRAPPER (LOCAL VERSION)'

# Ensure that SG Desktop is running
if [[ $(pgrep -u "$USER" Shotgun -c) == 0 ]]
then
  shotgrid_desktop
else
  echo "[INFO] ShotGrid Desktop already running."
fi

# tank (ShotGrid Toolkit) sets 'TANK_CURRENT_PC' when it creates its
# environment. If this command was called from tank, then we want to launch
# the app in a detached shell so that ShotGrid Desktop does not freeze up.
args=""
if [ "$TANK_CURRENT_PC" != "" ]
then
    args="--detached"
fi

# Launch 3DE4 with any provided file arguments
launch 3de --add 3de_tools $args -- 3DE4 "$@"